Build: Add missing include where possible
Fixes Watcom builds:
  sort.c(111): Warning! W131: No prototype found for function 'write'
  sort.c(298): Warning! W131: No prototype found for function 'open'
  sort.c(111): Warning! W308: The function 'write' without prototyped parameters called
  sort.c(111): Note! N2002: 'write' defined in: sort.c(111)
  sort.c(298): Warning! W308: The function 'open' without prototyped parameters called
  sort.c(298): Note! N2002: 'open' defined in: sort.c(298)
  Error: Compiler returned a bad status compiling "sort.c"

Note:
  Turbo C does not have this include, but we are getting open() etc from
kitten anyway, so it doesn't matter.